name: Deploy App Gateway v2

on:
  workflow_dispatch:
    inputs:
      paramset:
        description: 'Parameter set from AppGWv2-Parameters.psm1'
        required: true
        type: choice
        options:
          - StandardAppGatewayParams
          - WAFAppGatewayParams
          - PrivateOnlyAppGatewayParams

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Install Az PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force -Scope CurrentUser -AllowClobber
          Import-Module Az

      - name: Deploy Application Gateway
        shell: pwsh
        run: |
          Import-Module ./AppGWv2/AppGWv2-Parameters.psm1 -Force
          $params = $StandardAppGatewayParams
          ./AppGWv2/Deploy-AppGWv2.ps1 @params

          ./AppGWv2/Deploy-AppGWv2.ps1 @params
