name: Deploy App Gateway v2

on:
  workflow_dispatch:
    inputs:
      paramset:
        description: 'Parameter set from AppGWv2-Parameters.psm1'
        required: true
        type: choice
        options:
          - StandardAppGatewayParams
          - WAFAppGatewayParams
          - PrivateOnlyAppGatewayParams

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Run PowerShell Deployment
        shell: pwsh
        run: |
          # Import helper modules
          Import-Module ./Common-Modules/ValidationHelpers.psm1 -Force
          Import-Module ./Common-Modules/ConfigurationHelpers.psm1 -Force
          Import-Module ./AppGWv2/AppGWv2-Parameters.psm1 -Force

          $paramSetName = "${{ github.event.inputs.paramset }}"
          Write-Host "Using parameter set: $paramSetName"

          # Retrieve the chosen parameter set as a hashtable
          $params = Get-Variable -Name $paramSetName -ValueOnly

          # Deploy
          ./AppGWv2/Deploy-AppGWv2.ps1 @params
